### PR TITLE
fix(kuwo): use node to calc secret

### PR DESCRIPTION
**Pull request by foamzou**

### CODE REVIEW

**Comment by stkevintan** [comment]
So that means the program requires external NodeJS install? That may confuse users as we never document it. 
Curious about the reason of the decision since it's not a great job to translate js into go (I can contribute if help need)

**Comment by foamzou** [comment]
@stkevintan 
Thank you for noticing this change. Since it's been a while, I'll try to recall the details: 

1. As shown in the diff of this PR, we initially used a JS VM to run the JS code. However, we later discovered that in some cases, the computed signature was incorrect. The reason is that Kuwo's signature calculation involves a lot of floating-point operations, and the floating-point precision logic in Go's JS implementation differs from native JS. This caused deviations in digits several decimal places out. I tried several Go-based JS VMs, and all had this issue.

2. Only Kuwo relies on Node.js. This project is mainly used for my other open-source project, Melody, which runs on Node.js. So for most of my users, there's no issue with environment dependencies. As for the documentation, that was an oversight on my part—I'll add it.

**Comment by stkevintan** [comment]
Interesting, never met such cases. As far as I know, nodejs is based on Google V8, have you tried this? https://github.com/rogchap/v8go

**Comment by foamzou** [comment]
I don't remember if I have studied this lib. If you have the energy to do testing or use other alternatives, I would be grateful.
Using the test case under the kuwo directory should be sufficient for testing.

**Pull request merged**
